version: "2"

linters:
  settings:
    depguard:
      rules:
        deprecated:
          deny:
            - pkg: "io/ioutil"
              desc: "The 'io/ioutil' package is deprecated. Use corresponding 'os' or 'io' functions instead."
    goconst:
      ignore-string-values: "any"


  enable:
    - depguard
    - dogsled
    - exhaustive
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - bodyclose
    - rowserrcheck
    - tparallel
    - unparam
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - lll
